### ISSUE TITLE
import JuMP.getvalue

### ISSUE THREAD

**Issue by bbrunaud** [plasmo-dev/Plasmo.jl#6]
```julia
WARNING: both Plasmo and JuMP export "getvalue"; uses of it in module SCSimulation must be qualified
ERROR: UndefVarError: getvalue not defined
```

**Comment by jalving** [comment]
v0.3.0 now imports JuMP.value to retrieve variable values.  Note that currently, a node variable must have its value queried like: 
`value(node,node[:x])` since variable values get stored on the node when solving an OptiGraph.  We will need to setup some kind of wrapper to use value the same way we would with JuMP.
